cam1:
  _target_: manimo.sensors.real_sense_camera.RealSenseCam
  camera_cfg:
    img_width: 640
    img_height: 480
    hz: 30
    name: "cam1"
    device_id: "220422302129"
    buffer_size: 1
    window_dur: null  # number of seconds to track in buffer
    warm_start:
      enabled: True
      frames: 60

cam2:
  _target_: manimo.sensors.real_sense_camera.RealSenseCam
  camera_cfg:
    img_width: 640
    img_height: 480
    hz: 30
    name: "cam2"
    device_id: "231622302006"
    buffer_size: 1
    window_dur: null  # number of seconds to track in buffer
    warm_start:
      enabled: True
      frames: 60

cam3:
  _target_: manimo.sensors.real_sense_camera.RealSenseCam
  camera_cfg:
    img_width: 640
    img_height: 480
    hz: 30
    name: "cam3"
    device_id: "031222070082"
    buffer_size: 1
    window_dur: null  # number of seconds to track in buffer
    warm_start:
      enabled: True
      frames: 60

cam4:
  _target_: manimo.sensors.real_sense_camera.RealSenseCam
  camera_cfg:
    img_width: 640
    img_height: 480
    hz: 30
    name: "cam4"
    device_id: "102422076289"
    buffer_size: 1
    window_dur: null  # number of seconds to track in buffer
    warm_start:
      enabled: True
      frames: 60
